"""teacher goal relations

Revision ID: 0e89f0ccb778
Revises: 54e36a8844c3
Create Date: 2020-02-23 23:58:27.612033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e89f0ccb778'
down_revision = '54e36a8844c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dic_goals',
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('rus_name', sa.String(length=50), nullable=True),
    sa.Column('emblem', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('goal')
    )
    op.create_table('teacher_goal_association',
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal'], ['dic_goals.goal'], ),
    sa.ForeignKeyConstraint(['id_teacher'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('goal', 'id_teacher')
    )
    op.drop_table('goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rus_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('emblem', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_teacher', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_teacher'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('goal')
    )
    op.drop_table('teacher_goal_association')
    op.drop_table('dic_goals')
    # ### end Alembic commands ###
