"""change DicGoal key to goal_key

Revision ID: 3c954e1d0791
Revises: a07735f5bdb0
Create Date: 2020-02-27 07:44:30.296616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c954e1d0791'
down_revision = 'a07735f5bdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name="dic_goals") as batch_op:
        batch_op.alter_column('goal', new_column_name='goal_key')
    with op.batch_alter_table(table_name="teacher_goal_association") as batch_op:
        batch_op.alter_column('goal', new_column_name='goal_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name="dic_goals") as batch_op:
        batch_op.alter_column('goal_key', new_column_name='goal')
    with op.batch_alter_table(table_name="teacher_goal_association") as batch_op:
        batch_op.alter_column('goal_key', new_column_name='goal')
    # ### end Alembic commands ###
