"""Initial migration

Revision ID: 444665008725
Revises: 
Create Date: 2020-02-23 00:24:53.308389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444665008725'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('free', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('rus_name', sa.String(length=50), nullable=True),
    sa.Column('emblem', sa.String(length=100), nullable=True),
    sa.Column('id_teacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_teacher'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('goal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('teachers')
    # ### end Alembic commands ###
