"""booking

Revision ID: 6a2db399aa3a
Revises: 0e89f0ccb778
Create Date: 2020-02-24 01:01:59.783909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2db399aa3a'
down_revision = '0e89f0ccb778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.Column('weekday_key', sa.String(length=3), nullable=False),
    sa.Column('time_of_day', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_teacher'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['weekday_key'], ['dic_days_of_week.weekday_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('teacher_weekday_tod_idx', 'booking', ['id_teacher', 'weekday_key', 'time_of_day'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('teacher_weekday_tod_idx', table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
