"""add cleint info into booking

Revision ID: f5d960fb5132
Revises: 3c954e1d0791
Create Date: 2020-03-01 08:55:25.489388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d960fb5132'
down_revision = '3c954e1d0791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('client_name', sa.String(length=100)))
    op.add_column('booking', sa.Column('client_phone', sa.String(length=50)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'client_phone')
    op.drop_column('booking', 'client_name')
    # ### end Alembic commands ###
